
name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-windows-python:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.8"
          - python-version: "3.10"

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r dev-requirements.txt
        pip install -e . --config-settings editable_mode=strict # required for mypy/pyright to detect editable install
        pip list

    - name: run tests
      run: |
        pytest -v

